---
ansible_ssh_user: centos
ansible_user: centos
ansible_connection: ssh
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_become_user: root
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python2.7
hadoop_mirror_url: http://jvcdp.mywire.org
hadoop_version: 2.7.7
hive_mirror_url: http://jvcdp.mywire.org
hive_version: 2.3.4
spark_mirror_url: http://jvcdp.mywire.org
spark_version : '2.4.0'
spark_hadoop_version : hadoop2.7
zookeeper_mirror_url: http://archive.apache.org/dist/zookeeper
zookeeper_version: 3.4.6
install_base_dir: /usr/local
data_dir: /data/hadoop
openjdk_version: 1.8.0
start_hdfs_services: 'no'
alluxio_mirror_url: http://jvcdp.mywire.org/alluxio
alluxio_version: '1.8.1'

ldap_adm_id: ldapadm
root_dns_hosted_zone: amitthk.com
krb_default_realm: ldap.amitthk.com
ldap_server_rootpw: changethis
krb_kdc_root_db_pw: "{{ldap_server_rootpw}}"
mariadb_root_password: "{{ldap_server_rootpw}}"
mariadb_scm_password: "{{ldap_server_rootpw}}"
time_stamp: "{{'%Y%m%d%H%M%S' | strftime(ansible_date_time.epoch)}}"
harden_default_password: "{{time_stamp}}"

#the inventory contains the ips. Take out the first ip in the list
ldap_host_ip: "{{hostvars[groups['ldap'][0]]['inventory_hostname']}}"