---
- name: Prerequisites
  gather_facts: no
  hosts: all
  roles:
    - { name: common, become: yes, become_user: root, become_method: sudo }
  tags:
    - common

- name: core-settings
  gather_facts: no
  hosts: all
  roles:
    - { name: core-settings, become: yes, become_user: root, become_method: sudo }
  tags:
    - common

- name: db
  hosts: all
  become: yes
  roles:
    - { name: db, become: yes, become_user: dbadmin, become_method: sudo }
  tags:
    - db

- name: ldap
  hosts: all
  become: yes
  roles:
    - { name: ldap, become: yes, become_user: ldapadmin, become_method: sudo }
  tags:
    - ldap

- name: phpldapadmin
  hosts: all
  become: yes
  roles:
    - { name: phpldapadmin, become: yes, become_user: ldapadmin, become_method: sudo }
  tags:
    - phpldapadmin

- name: kerberos
  hosts: all
  become: yes
  roles:
    - { name: kerberos, become: yes, become_user: kerberos, become_method: sudo }
  tags:
    - kerberos