---
- name: Prerequisites
  gather_facts: no
  hosts: all
  roles:
    - { name: common, become: yes, become_user: root, become_method: sudo }
  tags:
    - common

- name: db
  hosts: all
  become: yes
  roles:
    - { name: db, become: yes, become_user: dbadmin, become_method: sudo }
  tags:
    - db