---
- name: Prerequisites
  gather_facts: yes
  hosts: all
  become: yes
  remote_user: "{{ansible_ssh_user}}"
  become_method: "{{ansible_become_method}}"
  become_user: "{{ansible_become_user}}"
  roles:
    - common
  tags:
    - common